### ISSUE TITLE
Придумать и реализовать архитектуру взаимодействия механики и графики. 

### ISSUE THREAD

**Issue by basilefff** [Ivan-Sergeyev/the-labyrinth#7]
Текущая система, которая заключается  во включени механики в графику не гибка и приводит к таким ошибка, как неинициализированная механика.

**Comment by Ivan-Sergeyev** [comment]
copy-paste from vk messages:

нам надо устроить общение игроков с gamestate'ом и gamestate'а с игроками
представь себе мультиплеер
для общения создаём i/o структуру
один конец присоединён к gamestate'у, другой — к игрокам
игроки закидывают запросы на ход и ждут ответа
закидывают в свою io структуру
она посылает сообщение по сети
сообщение приходит в соответствующую io структуру на другом конце
она общается с gamestate'ом
отправляет ответ назад
вот
сейчас у нас есть путаница, потому что class player — это не сам игрок (не конец структуры для общения), а фишка, которая у gamestate'а стоит на карте

this is for the future, when the game is up and running with working graphics and when it is time to implement multiplayer

**Comment by Ivan-Sergeyev** [comment]
new structure - see wiki page
the implementation of structure has been completed in 1ee8618aaa6e7842a21deaf0cf7be58af923283e
there are still leftover tasks, e.g. #11
